---
  AWSTemplateFormatVersion: 2010-09-09
  Description: S3 bucket creation
  Parameters:
    ConfigS3BucketName:
      Description: >-
          S3 bucket for Config
      Type: 'String'
      MinLength: 5
      MaxLength: 100
      Default: 'vw-cred-datalake-dev-s3-mlops-config'
    TagTeam:
      Description: >-
          Random character for Config
      Type: 'String'
      MinLength: 1
      MaxLength: 1000
      Default: 'itdna'
    TagProduct:
      Description: >-
          Random character for Config
      Type: 'String'
      MinLength: 1
      MaxLength: 1000
      Default: 'dl'
    TagTenant:
      Description: >-
          Random character for Config
      Type: 'String'
      MinLength: 1
      MaxLength: 1000
      Default: 'vw-cred-datalake'
    Environment:
      Description: >-
          Random character for Config
      Type: 'String'
      MinLength: 1
      MaxLength: 1000
      Default: 'init'  
  Resources:
    
    ConfigS3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: !Ref ConfigS3BucketName
        Tags:
          -
            Key: "vci:team"
            Value: !Ref TagTeam
          -
            Key: "vci:product"
            Value: !Ref TagProduct
          -
            Key: "tenant"
            Value: !Ref TagTenant
          -
            Key: "env"
            Value: !Ref Environment
    